services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - .env
    depends_on:
      - mysql-db

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-db:
    image: mysql:8.0
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data: